apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cut-one-pod
  namespace: demo
spec:
  podSelector:
    matchLabels:
      chaos: cut
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
